SehatClone/Models/Center.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SehatClone.Models
{
    public class Center
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public CenterType Type { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string ImageUrl { get; set; }
        public List<CenterServices> Services { get; set; }
        public string ForGender { get; set; }
        public string Timings { get; set; }
        public string Description { get; set; }

        public bool IsApproved { get; set; }

        public Center()
        {
            Services = new List<CenterServices>();
            ForGender = "Both Male and Female";
            ImageUrl = "/Content/images/no-image.jpg";
        }
    }
}

SehatClone/Models/CenterType.cs
namespace SehatClone.Models
{

    public class CenterType
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

SehatClone/Controllers/CentersController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using SehatClone.Models;

namespace SehatClone.Controllers
{
    public class CentersController : Controller
    {
        readonly ApplicationDbContext db;

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public CentersController()
        {
            db = new ApplicationDbContext();
        }

        public ActionResult Detail(int id)
        {
            var center = db.Centers.Include(c => c.Services)
                            .SingleOrDefault(c => c.Id == id);

            if (center == null)
                return HttpNotFound("Center Not Found");

            return View(center);
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Register(Center center)
        {
            if (!ModelState.IsValid)
                return View(center);

            db.Centers.Add(center);
            db.SaveChanges();

            var user = new ApplicationUser { UserName = center.Email, Email = center.Email };
            var result = await UserManager.CreateAsync(user, center.Password);
            if (result.Succeeded)
            {
                //await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                return RedirectToAction("Login");
            }

            foreach (var error in result.Errors)
                ModelState.AddModelError("", error);

            return View(center);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var center = db.Centers.SingleOrDefault(d => d.Email == model.Email && d.Password == model.Password);

            if (center == null)
            {
                ModelState.AddModelError("", "Invalid login attempt.");
                return View(model);
            }

            if (!center.IsApproved)
            {
                ModelState.AddModelError("", "Not Approved By Admin Yet");
                return View(model);
            }

            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToAction("Index", "Home");
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }
    }
}

SehatClone/Views/Centers/Detail.cshtml
@model SehatClone.Models.Center
@{
    ViewBag.Title = "Center Detail";
}

<h2 class="text-center">Center Detail</h2>
<hr />

<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="box doctor">
                <div class="row">
                    <div class="col-sm-4">
                        <img src="@Model.ImageUrl" alt="Doctor Image" class="img-circle img-responsive" />
                    </div>
                    <div class="col-sm-6 col-sm-offset-1">
                        <h3>
                            <strong>Name : </strong>
                            @Model.Name
                        </h3>
                        <h5>
                            <strong>Contact Name : </strong>
                            @Model.ContactName
                        </h5>
                        <h5>
                            <i class="glyphicon glyphicon-map-marker"></i>
                            @Model.City
                        </h5>
                        <h5>
                            <i class="glyphicon glyphicon-phone"></i>
                            @Model.Phone
                        </h5>
                    </div>
                </div>
            </div>
            <div class="box">
                <h3>Description</h3>
                @if (!string.IsNullOrEmpty(Model.Description))
                {
                    <p class="alert alert-info">
                        @Model.Description
                    </p>
                }
                else
                {
                    <div class="alert alert-info">
                        No Description Available
                    </div>
                }

            </div>
            <br />
            <div class="box">
                <h3>Services</h3>
               @if (Model.Services.Count > 0)
               {
                <ul class="list-group">
                    @foreach (var serivce in Model.Services)
                    {
                        <li class="list-group-item">
                            @serivce.Name
                        </li>
                    }
                </ul>
               }
               else
               {
                   <div class="alert alert-info">
                       No Services To Show
                   </div>
               }
            </div>

            <br />

            <div class="box">
                <h3>Timings</h3>
                @if (!string.IsNullOrEmpty(Model.Description))
                {
                    <p class="alert alert-info">
                        @Model.Timings
                    </p>
                }
                else
                {
                    <div class="alert alert-info">
                        No Timings Available
                    </div>
                }
            </div>

            <br />

            <div class="box">
                <h3>General Info</h3>
                @if (!string.IsNullOrEmpty(Model.Description))
                {
                    <p class="alert alert-info">
                        For @Model.ForGender
                    </p>
                }
                else
                {
                    <div class="alert alert-info">
                        No General Info Available
                    </div>
                }
            </div>
        </div>
    </div>

</div>

SehatClone/Views/Centers/Login.cshtml
@using SehatClone.Models
@model LoginViewModel
@{
    ViewBag.Title = "Center Log in";
}

<div class="container">
    <h2>@ViewBag.Title.</h2>

    <div class="row">
        <div class="col-md-8">
            <section id="loginForm">
                <form method="post" action="@Url.Action("Login" ,"Centers")">

                    @Html.AntiForgeryToken()
                    <h4>Use a local account to log in.</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <br />
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <div class="checkbox">
                                @Html.CheckBoxFor(m => m.RememberMe)
                                @Html.LabelFor(m => m.RememberMe)
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Log in" class="btn btn-default" />
                        </div>
                    </div>
                    <p>
                        @Html.ActionLink("Register as a new user", "Register")
                    </p>
                </form>

            </section>
        </div>
        @*<div class="col-md-4">
            <section id="socialLoginForm">
                @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
            </section>
        </div>*@
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SehatClone/Views/Centers/Register.cshtml
@model SehatClone.Models.Center

@{
    ViewBag.Title = "Register";
}

<h2 class="text-center">Register new Center</h2>
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}