SehatClone/Models/Article.cs
using System;

namespace SehatClone.Models
{
    public class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public ArticleCategory Type { get; set; }
        public DateTime DateTime { get; set; }
    }
}

SehatClone/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using SehatClone.Models;
using SehatClone.ViewModel;

namespace SehatClone.Controllers
{
    [Authorize]
    public class ArticlesController : Controller
    {
        readonly ApplicationDbContext db;

        public ArticlesController()
        {
            db = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            var articles = db.Articles.Include(a => a.Type)
                                .OrderByDescending(a => a.Id).ToList();
            return View(articles);
        }

        [AllowAnonymous]
        public ActionResult Show(string article)
        {
            var articles = new List<Article>();
            if (!string.IsNullOrEmpty(article))
                articles = db.Articles.Include(a => a.Type).Where(a => a.Title.ToLower().Contains(article.ToLower())).ToList();
            else
                articles = db.Articles.Include(a => a.Type).ToList();

            return View(articles.OrderByDescending(a => a.Id));
        }

        public ActionResult Create()
        {
            var vm = new CreateArticleVm
            {
                Categories = db.ArticleCategories.ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(CreateArticleVm vm)
        {
            if (!ModelState.IsValid)
                return View(vm);

            var cat = db.ArticleCategories.SingleOrDefault(a => a.Id == vm.Type);

            var article = new Article
            {
                Title = vm.Title,
                Content = vm.Content,
                DateTime = DateTime.Now,
                Type = cat
            };

            db.Articles.Add(article);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var article = db.Articles.Find(id);

            if (article == null)
                return HttpNotFound("Article not Found !");

            db.Articles.Remove(article);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

SehatClone/Views/Articles/Create.cshtml
@model SehatClone.ViewModel.CreateArticleVm

@{
    ViewBag.Title = "Create";
}

<h2 class="text-primary text-center">Create Article</h2>

<div class="container">

    <div class="row">
        <div class="col-sm-8">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label" })
                        @Html.TextAreaFor(model => model.Content, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.Type, new SelectList(Model.Categories, "Id", "Name"), new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-3 col-sm-offset-5">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>

</div>

SehatClone/Views/Articles/Index.cshtml
@model IEnumerable<SehatClone.Models.Article>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-primary text-center">Articles</h2>

<div class="container">

    <p>
        <a class="btn btn-primary" href="@Url.Action("Create", "Articles")">Create</a>
    </p>

    @if (Model.Count() > 0)
    {
        <div class="row">
            <div class="col-sm-12">

                <table class="table table-striped">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Content)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Type)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DateTime)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var article in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => article.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => article.Content)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => article.Type.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => article.DateTime)
                            </td>
                            <td>
                                @*@Html.ActionLink("Edit", "Edit", new { id = article.Id }) |*@
                                <a class="btn btn-danger" href="@Url.Action("Delete", "Articles", new { id = article.Id })">
                                    Delete
                                </a>
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                    No Articles To Show
                </div>
            </div>
        </div>
    }

</div>

SehatClone/Views/Articles/Show.cshtml
@model IEnumerable<SehatClone.Models.Article>
@{
    ViewBag.Title = "Articles";
}

<h2 class="text-center text-primary">Articles</h2>
<hr />

<div class="container">

    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form action="@Url.Action("Show", "Articles")">
                <input placeholder="Enter Article Title" type="text" class="form-control" name="article" />
                <br />
                <input type="submit" value="Search" class="btn btn-primary" />
            </form>
            
        </div>
    </div>
    <br />
    <br />

    @foreach (var article in Model)
    {
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h5 class="pull-right">
                            @article.DateTime.ToShortDateString()
                        </h5>
                        <h1 style="font-size: 1.7em;" class="panel-title">
                            @article.Title
                        </h1>
                        <h5>@article.Type.Name</h5>
                    </div>
                    <div class="panel-body">
                        @article.Content
                    </div>
                </div>
            </div>
        </div>
    }
</div>